name: prometheus-k8s
version: 0.0.1
description: Deploy a full prometheus monitoring stack for k8s
keywords:
  - prometheus
  - grafana
home: http://github.com/tcolgate/prometheus-k8s
maintainers:
  - name: Tristan Colgate-McFarlane
    email: tcolgate@gmail.com
engine: gotpl
