apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: pushgateway
  name: pushgateway
spec:
  selector:
    app: pushgateway
  type: NodePort
  ports:
  - name: pushgateway
    protocol: TCP
    port: 9091
    nodePort: 30901
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      name: pushgateway
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        ports:
        - name: web
          containerPort: 9091
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9091
          initialDelaySeconds: 15
          timeoutSeconds: 1
