kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana001
  labels:
    type: local
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data/data01"
