apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      name: blackbox
      labels:
        app: blackbox
    spec:
      containers:
      - name: blackbox
        image: prom/blackbox-exporter:latest
        args:
{{ range $k, $v  := .Values.args }}
          - '-{{$k}}={{$v}}'
{{ end }}
        ports:
        - name: web
          containerPort: 9115
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9115
          initialDelaySeconds: 15
          timeoutSeconds: 1
