apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
          - '-config.file=/etc/prometheus/alertmanager.yml'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9093
          initialDelaySeconds: 15
          timeoutSeconds: 1
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
