kind: PersistentVolume
apiVersion: v1
metadata:
  name: prom001
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/sda1/data/data00"
