apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      name: pushgateway
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        args:
{{ range $k, $v  := .Values.args }}
          - '-{{$k}}={{$v}}'
{{ end }}
        ports:
        - name: web
          containerPort: 9091
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9091
          initialDelaySeconds: 15
          timeoutSeconds: 1
