apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: statsd
  name: statsd
spec:
  selector:
    app: statsd
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 9102
    nodePort: 30912
  - name: statsd
    protocol: UDP
    port: 9125
    nodePort: 30825
