apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd
  template:
    metadata:
      name: statsd
      labels:
        app: statsd
    spec:
      containers:
      - name: statsd
        image: prom/statsd-exporter:latest
        ports:
        - name: web
          containerPort: 9102
        - name: statsd
          containerPort: 9125
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9102
          initialDelaySeconds: 15
          timeoutSeconds: 1
